name       : argon2
version    : '20171227'
release    : 1
source     :
    - https://github.com/P-H-C/phc-winner-argon2/archive/20171227.tar.gz : eaea0172c1f4ee4550d1b6c9ce01aab8d1ab66b4207776aa67991eb5872fdcd8
license    :
    - Apache-2.0
    - CC0-1.0
component  : security.crypto
summary    : The password hash Argon2, winner of PHC
description: |
    Argon2 is a password-hashing function that summarizes the state of the art in the design of memory-hard functions and can be used to hash passwords for credential storage, key derivation, or other applications.
setup      : |
    sed -e "s|lib/@HOST_MULTIARCH@|lib%LIBSUFFIX%/libargon2|; s|@UPSTREAM_VER@|${version}|" -i libargon2.pc
build      : |
    %make LIBRARY_REL=lib%LIBSUFFIX%
install    : |
    %make_install LIBRARY_REL=lib%LIBSUFFIX%

    install -D -m00644 libargon2.pc $installdir/%libdir%/pkgconfig/libargon2.pc
    install -D -m00644 man/argon2.1 $installdir/usr/share/man/man1/argon2.1
    rm $installdir/%libdir%/*.a
check      : |
    %make test

